name: selinum-e2e test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies (web)
      working-directory: ./web
      run: npm install

    - name: Start Vite dev server
      working-directory: ./web
      run: npx vite --host 127.0.0.1 --port 8081 &

    - name: Wait for dev server to be ready
      run: npx wait-on http://127.0.0.1:8081 --timeout 60000

    - name: Install dependencies (tests)
      working-directory: ./collabroom-tests/selenium
      run: npm install

    - name: Run Selenium Tests
      working-directory: ./collabroom-tests/selenium
      run: npm test -- --json --outputFile=jest-results-ci.json
      continue-on-error: true

    - name: Upload Test Report (Excel)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-report-excel
        path: ./collabroom-tests/reports/selenium-report.xlsx

    - name: Upload Test Results (JSON)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: selenium-report-json
        path: ./collabroom-tests/selenium/jest-results-ci.json
